### ISSUE TITLE
Expanded card is opening and closing continuously

### ISSUE THREAD

**Issue by jcassee** [ljmerza/our-groceries-card#12]
Installed both the integration and the plugin today. This is the dashboard config:

```yaml
  - title: Boodschappen
    cards:
      - type: custom:our-groceries-card
        show_header: false
        expanded: true
```

Unfortunately, the card is flashing open and close continuously:
![Screencast-2020-04-26_23 16 59](https://user-images.githubusercontent.com/20749/80320297-e7a0fe80-8815-11ea-95bf-7f83523e7da2.gif)

Anything I can do to help debug this problem?
