### ISSUE TITLE
The option show_lists not working

### ISSUE THREAD

**Issue by Zubredo** [ljmerza/our-groceries-card#25]
Thank you for your great work! 

I don't geht the option show_lists to work. Using the code

`show_lists:
  - xxx`

in the our groceries card leads to an empty card. I tried several lists ids in several ways of writing (upper case, lower case, etc) but nothing seems to work.

Is there any way you can fix this?

**Comment by Danie10** [comment]
I'm having the same issue - Dev Tools shows the list names being returned even with correct activeCount, but actual shopping list items don't display for the card.

Can note though, if I remove the show_lists completely, then all lists do actually display OK. So it is a something to do with the that filter.

**Comment by haseat** [comment]
It works, but you cannot use the name of the shopping list, you have to use the id of the shopping list. You can find the id in developer tools/states:

```
shopping_lists: 
- activeCount: 0
  name: Shopping
  id: wGFJ5tcmYRCAxAcd4CU7K3
- activeCount: 3
  name: ToDo
  id: WhZfgo9fQnIo0toUhLVDaD
```
